---
- name: update repository index (CentOS)
  tags: always
  dnf:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "CentOS"
  become: true

- name: install updates (Ubuntu)
  tags: always
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "Ubuntu"
  become: true
